# -*- coding: utf-8 -*-
"""Customer_SupportRAGProject_depi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbpBazIIG2VxmavcbGG7gTnnsgwZJFED
"""

import pandas as pd
df=pd.read_csv('/content/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv.xls')
df.head()

"""data preprocessing"""

df.shape

df=df[['instruction','response']]
df.dropna(inplace=True)

df.drop_duplicates()
df.head()

"""1-*emdedding*"""

from sentence_transformers import SentenceTransformer
embed_model=SentenceTransformer('all-MiniLM-L6-v2')
instructions=df['instruction'].tolist()
embeddings=embed_model.encode(instructions,show_progress_bar=True)

!pip install faiss-cpu
import faiss
import numpy as np

dimensions=embeddings.shape[1]
index=faiss.IndexFlatL2(dimensions)
index.add(np.array(embeddings).astype("float32"))

def retrieve (query, k =3 ):
  query_vec = embed_model.encode([query])
  query_vec= np.array(query_vec).astype("float32")
  D, I  = index.search (query_vec, k)
  #I=[[15,3,4]]
  results=df.iloc[I[0]]
  #I=[15,3,4]
  return results

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-small")
gen_model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-small")

def generate_answer(prompt):
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = gen_model.generate(**inputs, max_new_tokens=50)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

#RAG
def rag_pipeline(query):
  retrieved = retrieve(query , k=3 )
  context = retrieved['response'].iloc[0]

  prompt = f"""
  Answer The Question using the context below.
  context:
  {context}

  Question:
  {query}

  Answer:
     """
  answer = generate_answer(prompt)

  return answer

rag_pipeline("cancel order")

!pip install pyngrok pydeck streamlit

from pyngrok import ngrok
ngrok.set_auth_token("35uLRYnpDiWFrJzrgDjqs7hN3pd_5qov5SGCc12dMtsHCJpgK")

"""Build Streamlit app"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import faiss
# from sentence_transformers import SentenceTransformer
# from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
# import re
# 
# 
# # Load Models
# @st.cache_resource
# def load_models():
#     embed_model = SentenceTransformer('all-MiniLM-L6-v2')
#     tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
#     llm_model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")
#     return embed_model, tokenizer, llm_model
# 
# 
# # Load Data
# @st.cache_data
# def load_data():
#     df = pd.read_csv('/content/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv.xls')
#     df = df[['instruction', 'response']].dropna().drop_duplicates()
#     return df
# 
# 
# # Build Index
# @st.cache_resource
# def build_index(df, _model):
#     embeddings = _model.encode(df['instruction'].tolist())
#     embeddings = np.array(embeddings).astype("float32")
# 
#     dimension = embeddings.shape[1]
#     index = faiss.IndexFlatL2(dimension)
#     index.add(embeddings)
# 
#     return index
# 
# 
# # Retrieve
# def retrieve(query, model, index, df, k=3):
#     query_vec = model.encode([query]).astype("float32")
#     D, I = index.search(query_vec, k)
#     return df.iloc[I[0]]
# 
# # RAG Pipeline
# def rag_pipeline(query, embed_model, index, df, tokenizer, llm_model):
# 
#     retrieved = retrieve(query, embed_model, index, df, k=3)
#     contexts = " ".join(retrieved['response'].tolist())
# 
#     prompt = f"""
# You are a professional customer support assistant.
# Provide a clear, detailed, and complete answer based ONLY on the context below. Include steps if available.
# 
# Context:
# {contexts[:1500]}
# 
# Question:
# {query}
# 
# Answer:
# """
# 
#     inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
# 
#     outputs = llm_model.generate(
#         **inputs,
#         max_new_tokens=250,
#         do_sample=False,
#         repetition_penalty=1.2
#     )
# 
#     answer = tokenizer.decode(outputs[0], skip_special_tokens=True).strip()
# 
#     if len(answer) < 30 or query.lower() in answer.lower():
#         answer = max(retrieved['response'].tolist(), key=len)
# 
#     answer = answer.replace("\n", " ")
#     answer = re.sub(r"\{\{.*?\}\}", "", answer)
# 
#     return answer
# 
# 
# # UI
# st.set_page_config(page_title="S3 Chatbot", page_icon="🤖")
# st.title("🤖 Customer Support Chatbot")
# 
# embed_model, tokenizer, llm_model = load_models()
# df = load_data()
# index = build_index(df, embed_model)
# 
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# 
# for msg in st.session_state.messages:
#     st.chat_message(msg["role"]).write(msg["content"])
# 
# if prompt := st.chat_input("Ask anything ....."):
#     st.session_state.messages.append({"role": "user", "content": prompt})
#     st.chat_message("user").write(prompt)
# 
#     with st.chat_message("assistant"):
#         with st.spinner("Thinking..."):
#             response = rag_pipeline(prompt, embed_model, index, df, tokenizer, llm_model)
#             st.markdown(response)
# 
#     st.session_state.messages.append({"role": "assistant", "content": response})

get_ipython().system_raw('streamlit run app.py &')
public_url = ngrok.connect(8501)
print(public_url)